### ISSUE TITLE
Build failing with the latest 2.0.0 version (iOS)

### ISSUE THREAD

**Issue by Firzenizer** [stetro/cordova-plugin-fcm-config#2]
I am getting this error with the new version 2.0.0 of the cordova-plugin-fcm.

iOS build fails to copy plist. When I removed your plugin it built successfully and ipa contained plist. But it was full of jiberish. Maybe the cordova-plugin-fcm now copies the file and your plugin conflicts with it?

```
The following build commands failed:
CopyPlistFile build/EventosMobile.app/GoogleService-Info.plist EventosMobile/Plugins/cordova-plugin-fcm-config/GoogleService-Info.plist
(1 failure)
```

**Comment by stetro** [comment]
Your are right, as written in https://github.com/fechanique/cordova-plugin-fcm Version 2.0 has this feature included: 
> 'google-services.json' and 'GoogleService-Info.plist' are added automatically from Cordova project root to platform folders

I will add an info about it in the README

**Comment by Firzenizer** [comment]
That has probably been there for long time. It doesn't work on PGB. PhoneGap Build will just ignore all files except config.xml in root directory.

**Comment by themagicclicks** [comment]
Firzenizer did you find any solution to this problem on PGB?

**Comment by DanRobinsonRV** [comment]
I'm also still experiencing this problem on PhoneGap build, I'm trying to use it as per [this SO answer](https://stackoverflow.com/a/39756068/1482673). I appreciate it's not really an intended use case for this plugin, but did anyone ever find an answer?
