### ISSUE TITLE
error in phonegap build

### ISSUE THREAD

**Issue by BrunoGiubilei** [stetro/cordova-plugin-fcm-config#4]
i try to use your plugin, but its doesnt work for me, this is my project configuration, and my steps to built .apk file:

its my estructure folder

- www/
  -   cordova-plugin-fcm-config/
      - google-services.json/ -> i am replace for my version of this file
      - //anothers files from your repository
  - css/
  - img/
  - js/
  - res/
  - 404.html
  - config.xml
  - favicon.ico
  - index.html
  - main.html
------------------------------------------------------------------------------------------------------------------------------------------

part of my config.xml file:

plugin name="cordova-plugin-fcm-config" spec="cordova-plugin-fcm-config" /
preference name="android-build-tool" value="gradle" /
preference name="android-minSdkVersion" value="14" >
gap:plugin name="cordova-plugin-fcm" source="npm" /

------------------------------------------------------------------------------------------------------------------------------------------

after this, i am create a www.zip file, and upload to build.phonegap.com

and i am get this error:

Build Date: 2017-04-17 15:47:08 +0000
--------------------------------------------------------------------------------
PLUGIN OUTPUT
--------------------------------------------------------------------------------
Fetching plugin "cordova-plugin-whitelist" via npm
Installing "cordova-plugin-whitelist" at "1.3.2" for android

               This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.
Fetching plugin "cordova-plugin-device" via npm
Installing "cordova-plugin-device" at "1.1.5" for android
Fetching plugin "cordova-plugin-app-version" via npm
Installing "cordova-plugin-app-version" at "0.1.9" for android
Fetching plugin "cordova-plugin-network-information" via npm
Installing "cordova-plugin-network-information" at "1.3.2" for android
Fetching plugin "cordova-plugin-crosswalk-webview" via npm
Installing "cordova-plugin-crosswalk-webview" at "2.3.0" for android
Subproject Path: CordovaLib

        After much discussion and analysis of the market, we have decided to discontinue support for Android 4.0 (ICS) in Crosswalk starting with version 20.

        So the minSdkVersion of Cordova project is configured to 16 by default.
Fetching plugin "cordova-plugin-x-socialsharing" via npm
Installing "cordova-plugin-x-socialsharing" at "5.1.7" for android
Subproject Path: CordovaLib
Fetching plugin "cordova-plugin-file-transfer" via npm
Installing "cordova-plugin-file-transfer" at "1.6.2" for android
Fetching plugin "cordova-plugin-file" via npm
Installing "cordova-plugin-file" at "4.3.2" for android
Fetching plugin "cordova-plugin-compat" via npm
Installing "cordova-plugin-compat" at "1.1.0" for android

The Android Persistent storage location now defaults to "Internal". Please check this plugin's README to see if your application needs any changes in its config.xml.

If this is a new application no changes are required.

If this is an update to an existing application that did not specify an "AndroidPersistentFileLocation" you may need to add:

      "<preference name="AndroidPersistentFileLocation" value="Compatibility" />"

to config.xml in order for the application to find previously stored files.
Fetching plugin "cordova-plugin-fcm" via npm
Installing "cordova-plugin-fcm" at "2.1.1" for android
Subproject Path: CordovaLib

		Cordova FCM plugin v2.1.1 installed
		For more details visit https://github.com/fechanique/cordova-plugin-fcm
"plugman install --platform android --project /project --plugin cordova-plugin-fcm-config@cordova-plugin-fcm-config": Fetching plugin "cordova-plugin-fcm-config@cordova-plugin-fcm-config" via npm
Failed to fetch plugin cordova-plugin-fcm-config@cordova-plugin-fcm-config via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: No compatible version found: cordova-plugin-fcm-config@'cordova-plugin-fcm-config'
Valid install targets:
["1.0.0"]

**Comment by sayacan** [comment]
any solution? have same problems

**Comment by ccomai92** [comment]
Me too

**Comment by BrunoGiubilei** [comment]
for anyone who get any error with phonegap or cordova building, look for solutions who can do the dirt job for this like webpack, much better and faster
